CREATE TABLE UsersLog (
    LogId SERIAL,
    UserId INTEGER NOT NULL,
    LoginTimestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ActivityType VARCHAR(10) NOT NULL,

    CONSTRAINT USERS_LOG_PKEY PRIMARY KEY (LogId),
    CONSTRAINT USERS_LOG_ACTIVITYTYPE_CHECK CHECK (ActivityType IN ('LOGIN', 'LOGOUT')),
    CONSTRAINT USERS_LOG_USERID_FKEY FOREIGN KEY(UserId)
        REFERENCES USERS(Userid)
        ON DELETE CASCADE
);